version: '3.8'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:${SQLSERVER_VERSION?:error}
    restart: always
    ports:
      - ${SQLSERVER_PORT?:error}:1433
    env_file: 
      - .env
