version: "3.4"

services:
  postgresdb:
    image: mongo:${MONGO_VERSION}
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./.data:/data/db
      # - type: bind # this syntax requires "data" to be created beforehand
      #   source: ./data
      #   target: /var/lib/postgresql/data
